Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "windows2016"
  c.vm.hostname = "windows2016"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-win_server_security_standards-security-enforcement-windows2016"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
